- index.html
> add icon tab to index

- css/team.css
- team.html
> add team.html

- team.html
> added image and details to team page

- team.html
Added pictures to the third row, after the digital marketing track. 
Sorry, no screenshot. My device is down.
> Included my picture from cloudinary

- team.html
> updated my profile and added my track

- team.html
> i added my profile

- team.html
https://res.cloudinary.com/majeks/image/upload/v1567239786/startng/Capture1_dohr6a.png
> Moridiya Update with my picture, name and track

- team.html
Sorry, my device is down. No screenshot.
> Added my image from Cloudinary.

- about.html
- css/about.css
- css/team.css
- team.html
I edited the about and team page. 
click [here](https://res.cloudinary.com/ibrahimygana/image/upload/v1567248752/START%20NG/v5wtpmie1q5q6f3ikdqr.png) to view the "About page".
click [here](https://res.cloudinary.com/ibrahimygana/image/upload/v1567248809/START%20NG/mw7jqukd2isqsbbpqbmp.png) to view the "Team page".
> Edited the about and team page

- team.html
I've updated the team.html with my profile picture, name, and track.
> add profile

- team.html
I updated team.html with my cloudinary link , my name and my team.
Serial number on team sheet: 37.
> Updated team.html #37

- team.html
> Successfully updated team.html

- team.html
> my picture was added

- team.html
I added my cloudinary image link and updated my profile on team.html
> add-Gladys-profile

- team.html
> Add Horacewillie profile

- css/successful.css
- successful.html
Updated succesful.html and styled it with CSS.
> Updated successful.html

- team.css
- team.html
> first commit

- about.html
- css/about.css
- css/contact.css
- index.html
- style.css
Images reduced from 904kb to 371kb
> Landing page images optimized

- css/project.css
- project.html
> I edited the projects page using html and some css

- team.html
> updated my profile (Joshua Folorunsho)

- team.html
updated my profile  with website, contribution and shn code
> dennismarie profile update

- css/donation.css
- donation.html
Slack username: @Valar Dohaeris.
I updated the donation page by adding the header background picture and styling it. I also added the picture below the `Donate Now` button.
> Updating donation page.

- team.html
added my details and okeseyi's details
> updated team details by taofeeq-deru

- README.md
- about.html
- contact.html
- css/about.css
- css/contact.css
- css/project.css
- donation.html
- index.html
- project.html
- style.css
- team.html
Created the Project page.
Added my details to team.html
new styling in css/project.css & style.css
Project Page>> https://user-images.githubusercontent.com/29564545/64292663-c88ded80-cf62-11e9-9778-13841b7457e8.png
> Projects page, Added details to team page

- team.html
I Updated my Profile with my contribution to GiftaPad project and also my link to my CV
> Latest Update

- team.html
> i updated the team info with my details

- team.html
> I added my webpage to my profile in the team page

- team.html
> Updating Team.html
